
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectphoenix-app-deployment  # Unique name for the deployment
  labels:
    app: projectphoenix-app # Label to identify the application
spec:
  replicas: 3 # Number of desired replicas for high availability
  selector:
    matchLabels:
      app: projectphoenix-app # Select pods with this label
  strategy:
    type: RollingUpdate # Recommended for smooth updates
    rollingUpdate:
      maxUnavailable: 1 #  Specifies the maximum number of pods that can be unavailable during the update
      maxSurge: 1 #  Specifies the maximum number of pods that can be created above the desired number of pods
  template:
    metadata:
      labels:
        app: projectphoenix-app # Labels applied to the pods
    spec:
      containers:
      - name: projectphoenix-app-container # Name of the container
        image: projectphoenix-docker-registry/projectphoenix-app:latest #  Container image with version tag
        ports:
        - containerPort: 8080 #  Port the application listens on
        resources:
          requests: # Guaranteed resources the container needs
            cpu: 100m # 0.1 CPU core
            memory: 128Mi # 128 MiB of memory
          limits: # Maximum resources the container can consume
            cpu: 500m # 0.5 CPU core
            memory: 256Mi # 256 MiB of memory
        livenessProbe: # Checks if the container is healthy and running
          httpGet:
            path: /healthz #  Path to check for liveness
            port: 8080 # Port to check
          initialDelaySeconds: 15 #  Delay before the first liveness check
          periodSeconds: 10 #  How often to perform the check
        readinessProbe: # Checks if the container is ready to accept traffic
          httpGet:
            path: /ready # Path to check for readiness
            port: 8080 # Port to check
          initialDelaySeconds: 5 # Delay before the first readiness check
          periodSeconds: 5 # How often to perform the check
        env: # Environment variables
          - name: ENV_RISEPATH # Example environment variable
            value: up+forward
        volumeMounts: # Mount volumes to the container
          - name: projectphoenix-config-volume
            mountPath: /app/config
          - name: projectphoenix-data-volume
            mountPath: /app/data
      volumes: # Define volumes
        - name: projectphoenix-config-volume
          configMap: # Use a ConfigMap for configuration data
            name: projectphoenix-app-config
        - name: projectphoenix-data-volume
          persistentVolumeClaim: # Use a PersistentVolumeClaim for persistent storage
            claimName: projectphoenix-app-pvc
      imagePullSecrets: # Pull secrets for private image registries
      - name: projectphoenix-registry-secret
      nodeSelector: # Schedule pods on specific nodes
        disktype: ssd
      tolerations: # Allow pods to run on tained nodes
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule"
      affinity: # Advanced scheduling rules
        podAntiAffinity: # Prefer to schedule pods on different nodes
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - my-app
              
