apiVersion: v1
kind: Namespace
metadata:
  name: ollama-system # Or your preferred namespace name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-rocm
  namespace: ollama-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-rocm
  template:
    metadata:
      labels:
        app: ollama-rocm
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: ollama
        image: ollama/ollama:rocm
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "ollama pull llama3.1"] # pre-pull model
        #- name: HSA_OVERRIDE_GFX_VERSION
        #  value: "10.3.0"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        resources:
          requests:
            amd.com/gpu: 1
          limits:
            amd.com/gpu: 1
      volumes:
      - name: ollama-data
        hostPath:
          path: /var/lib/ollama/.ollama
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service-rocm
  namespace: ollama-system
spec:
  selector:
    app: ollama-rocm
  ports:
  - protocol: TCP
    port: 11434
    targetPort: 11434
    name: ollama
  type: ClusterIP
