apiVersion: v1
kind: Pod
metadata:
  name: rocm-test-pod
spec:
  containers:
  - name: rocm-test-container
    image: rocm/tensorflow:latest
    command: ["sh", "-c", "rocm-smi"]
    resources:
      limits:
        amd.com/gpu: 1
  restartPolicy: Never
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
